[[ghr]]
arch = "aarch64"
git-tree-sha1 = "cc0db35f9b3a27d81330c6dcd34b0802dade1fde"
os = "macos"

    [[ghr.download]]
    sha256 = "b0b4e5bf252a20e2f4dd39509683af8e865bc0eaa7832076bd45f70a0eb4f16d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.aarch64-apple-darwin.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "1e316254ee4364ead125d278a3e5ba12f60ae4f4"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "9c43d2c8a84916ec19f799b71f5cfb4be87483be04611d5c439689dd9ca8b427"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.aarch64-linux-gnu.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "1e316254ee4364ead125d278a3e5ba12f60ae4f4"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "9c43d2c8a84916ec19f799b71f5cfb4be87483be04611d5c439689dd9ca8b427"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.aarch64-linux-musl.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e6144ea4aacc0f19d5845d9a597a43f94ebd03e"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "81842248e0db081aaf68151ea43b231042cae41296eb7fc8be83be1e925c9355"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.armv6l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e6144ea4aacc0f19d5845d9a597a43f94ebd03e"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "81842248e0db081aaf68151ea43b231042cae41296eb7fc8be83be1e925c9355"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.armv6l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0c5e1a062852ec0dfc2ebd03f50488164783251"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "3c7f92ceed5fda6483c285bfafea472ac51bb138fd6c99a793eabdff815f8bbf"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.armv7l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0c5e1a062852ec0dfc2ebd03f50488164783251"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "3c7f92ceed5fda6483c285bfafea472ac51bb138fd6c99a793eabdff815f8bbf"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.armv7l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "bdafc521b84807dd2e549bdad115bbc171a6fff0"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "87685f74d85cbdc3d92c9fa5c58830d8afa86a8d1964cb6ce79d58ef141383b5"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.i686-linux-gnu.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "bdafc521b84807dd2e549bdad115bbc171a6fff0"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "87685f74d85cbdc3d92c9fa5c58830d8afa86a8d1964cb6ce79d58ef141383b5"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.i686-linux-musl.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "427f567d2a71bf388f9451b84335375f2cddd5a1"
os = "windows"

    [[ghr.download]]
    sha256 = "f8539affb580ff1cc4c72eb4c85afaa23b9bf6ff7411fdf6841cd346f803abab"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.i686-w64-mingw32.tar.gz"
[[ghr]]
arch = "powerpc64le"
git-tree-sha1 = "b4a23c2d7ede40d502ec5ee4c5afbf8ae7c65a42"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "2090b88c5de7ac20aff84851d743d82f5b64c1e38b5a96617b42e023d80b9f7a"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.powerpc64le-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "e6d0d0e827f15f4cfc8a62dce621702a64d3c731"
os = "macos"

    [[ghr.download]]
    sha256 = "f7b6ffd58a96a1a117e226da64150806b12db6d728418d18f26276e701ae49c5"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.x86_64-apple-darwin.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "5f81fe80868ce064b2bf82977f9f3f329cbeff46"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "f6a8169f0103490539628e2c80514c2983014c18fdff23ddad4171fdd0b6c7f9"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.x86_64-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "c3c374f1ca99229e44be18fc4b3dd9ef02686dd0"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "1f00bb5cc0667f87becfa462800be779471dc232ac48693e64d54a4745110a66"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.x86_64-linux-musl.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "1e903481b0baea35a136b9997d74e90b99f051ea"
os = "freebsd"

    [[ghr.download]]
    sha256 = "3d4d6caded1038e1c19397149d4c6b20122ddaf5275679add81f94c075951d37"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.x86_64-unknown-freebsd.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "5fbf5819cc78caffb49149f290b92b9a57152713"
os = "windows"

    [[ghr.download]]
    sha256 = "93b75fc62189d2326f591581f43fbf5c23fea581c9842f9b3ca82fcce8c95c79"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.16.2+0/ghr.v0.16.2.x86_64-w64-mingw32.tar.gz"
