[[ghr]]
arch = "aarch64"
git-tree-sha1 = "03dee7cfb9bf1b9a7a2f29140f6373fee8a81c38"
os = "macos"

    [[ghr.download]]
    sha256 = "e0101accfa818c72b0d5ac8e83176b8d182e34a7487c49d7306b9b1563ef1624"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.aarch64-apple-darwin.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "f6ce6ec119fe3de92dfda3ed0a45fa8fac96b912"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "2c32db653a5804d69731ba03ad383988a88a44e6220d22bfa7a0e77aa454bdd0"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.aarch64-linux-gnu.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "7f67d976a1ed6bd32d3ba390c4747a012577abe5"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "2c005a8ce7055b05ad760896e95a047a0753447c0232f040f7937f45bbb2172f"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.aarch64-linux-musl.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12d5309e5aab39438aad1ae2fd7f4a34203752a3"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "ea4f86f8b727ecc6e8824d16aac70074b2babcb385bed84e05fec8a47c7ecce1"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.armv6l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0443e9e5d9e4e0d14e1118561659a731cf9b421a"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "debf184100a9a080f1a1ad92a2c549280e5f7d9e7c190c3f4103cad8591769c0"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.armv6l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b3d04fc6e7a63e9db6a6e87db4a9dc616ad52f8"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "f2775bcf078f6cd38987d0528e9416f305ee38f700375f7d99c745979d8fd76d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.armv7l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "110c786ecb65add131883b9ee789a6898d997281"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "6d06abe01a54d8e9c64a82ce68a6b41e4ffe8d83650c2d1f0ebb100b2fe5c493"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.armv7l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "8af507c4042d8a5322e56a05ce9a18e21a5275de"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "07a096cc24583972a8fdcd072663ad4b17da3c6bc92295ba545ee58c0374d83f"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.i686-linux-gnu.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "0954e06706de814f2a81a5d6f5ea939729127302"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "cdaecc3e4b2429f4f011a68244123b03c7399465527305ff35c86044a4dd459c"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.i686-linux-musl.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "e6f1e4fc4a71f402a9e23a8d7add83f8684402b7"
os = "windows"

    [[ghr.download]]
    sha256 = "ab37ea7f056ab414b77bdb7dfc0549d2fbfd7a89e0b36e95e6ee8729adbbb7f6"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.i686-w64-mingw32.tar.gz"
[[ghr]]
arch = "powerpc64le"
git-tree-sha1 = "d300c0a3d9aba8d8913cf51d3996ca17841b1ca7"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "448019a550e3da01feae6f1c0fe503e85b9215981dc07429c1ad847e12141e8f"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.powerpc64le-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "1bc0af717efc4628a0863729a08c53c7b1c0c184"
os = "macos"

    [[ghr.download]]
    sha256 = "905fd6b9c37ea4e43906c8889651e4bff2ef0040fe1e1847a920c946cb879a3d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.x86_64-apple-darwin.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "e6e29a96c9ba31b5b0c85a85b5456f5b8309e6be"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "741659a1f8529408882c8ffe9c80c34ded5dbc51529ab7546020f2283e48f00e"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.x86_64-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "7d615c47786732e7137d41a0fa8a64ed710fd505"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "a53bd2dd7857ea05c08792dbc1aca18efcff9d72789a9aecafcafb9f7e4bddec"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.x86_64-linux-musl.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "ae5e92aa7b59ca18b2a160b85b1afac4316f001a"
os = "freebsd"

    [[ghr.download]]
    sha256 = "ef72c6c3a970a14b31d32205aa95c7bb557ef25f10a1457dea8f6637687d056e"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "b087f86e5d82f72607178efedfc5b36d25277d08"
os = "windows"

    [[ghr.download]]
    sha256 = "e8469218a0e2a759cf39e58853529423d564d354e633b103644946cb29fe7fca"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.14.0+0/ghr.v0.14.0.x86_64-w64-mingw32.tar.gz"
