[[ghr]]
arch = "aarch64"
git-tree-sha1 = "97a7d6ecf94ed6c3689d24134c53ace43e90142d"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "d35573252816c4fc5f782dd1b171572c8afb6dc84be057ad759af54ae4db4292"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.aarch64-linux-gnu.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "9224b3f63317fab35affc48b7da70bbfb141d4b3"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "834e8fef1adad7e4f677cc8378928699382a339d525802e7041d669cd17b6c15"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.aarch64-linux-musl.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df6e9cc3d44a8b2bd86050eb8c868b329af2a007"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "02fdf019296f4312b8003db105d84f8e4a16dd3407efa89bfaff8e95235a77e6"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.armv7l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dbb886cbe4382bffbd235510d38923b34c64bdf4"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "429b6d21d1085a1c6e3b2b642893ea5f310afccec754fe46e9e4c14dad6d9b66"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.armv7l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "8e8c6680b4987b04860a4a95d73e556ccbc1af82"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "42773b8da9ae85ce1332ac3f84efc9313009609fa5e5a32268a98ade4070ff6b"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.i686-linux-gnu.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "02f8c679471bbc7fb399fd8d0827b48e05b75597"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "119fb91c7636133f8c9b7012b1a3ba3cb818aca81090f4a986003c552130a455"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.i686-linux-musl.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "cc4f6312b14b17825fd98963e2f550d709902f82"
os = "windows"

    [[ghr.download]]
    sha256 = "fcc79ca288a75357314a8b1cd8af438c02ab4c0ae1f8af5bdd5cd6f0e6455de5"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.i686-w64-mingw32.tar.gz"
[[ghr]]
arch = "powerpc64le"
git-tree-sha1 = "90e0b37983054042ec1f811cd7b749a00b6f19d4"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "182e17b81c8c369a2a05c1203b7768b243e31e1c54559fcbc9e2eb1ea17cc2ad"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.powerpc64le-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "8bb60e71163656604c1f7b3e590e1c1e802cdf26"
os = "macos"

    [[ghr.download]]
    sha256 = "faef281609d1209dc324e80dca0cd6e32dea4a23522f8b3465b70b47d897db15"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.x86_64-apple-darwin.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "803e4ff95ef62956f6077b94de075649fb2eb648"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "2df2872cfbf56e2a900bdadce6817aa8d5dc9635d3029ee7972d8e0910aca583"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.x86_64-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "83d59d0c8c721cd9d45f3023b0f882af4458e3aa"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "73101b87081702af3a00fa00a6b1ff59aa00511b49f67003679ae0ae647294ef"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.x86_64-linux-musl.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "257603a03aa2f66344b817f73d7662aa720fc778"
os = "freebsd"

    [[ghr.download]]
    sha256 = "6dd9fd4a373ed6c14e9d2b6e6aa4bd4e1d4a33a7061e11eeda04e87b1bac2fce"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.x86_64-unknown-freebsd.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "e2f69510e3e0db8096ec5101192e72efd167103e"
os = "windows"

    [[ghr.download]]
    sha256 = "95b408c5a356c067fdf164b9990f3dca015186c9845a94f201c7a810bd927f1c"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.13.0+1/ghr.v0.13.0.x86_64-w64-mingw32.tar.gz"
