[[ghr]]
arch = "aarch64"
git-tree-sha1 = "fc094879d12581483817e5757fef65ffbc8d520d"
os = "macos"

    [[ghr.download]]
    sha256 = "3382cb84b15dc55311d468db0fb3aa28cd4369341ca3106c7b00b17282d54260"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.aarch64-apple-darwin.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "49c35c590a0f865a172a4fca75727922fc5fe019"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "48c85ab18fe73e11977c7dbbff8e0ad8dc4725aa36e8413493080a120a52a3f4"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.aarch64-linux-gnu.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "49c35c590a0f865a172a4fca75727922fc5fe019"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "48c85ab18fe73e11977c7dbbff8e0ad8dc4725aa36e8413493080a120a52a3f4"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.aarch64-linux-musl.tar.gz"
[[ghr]]
arch = "aarch64"
git-tree-sha1 = "7c5942208929284e3685306d17067f516663c988"
os = "freebsd"

    [[ghr.download]]
    sha256 = "3dad680ab45d600c9ef59159f0f646c7f03634c7e96a64f1c126bc030c27b998"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.aarch64-unknown-freebsd.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f1049b42726c23bbd44826feaee1ed7ebb465ce"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "621f4ec66fb81b29470d3b30fba2ea5041db29f905e9f3fe95c3ea7c00bab80d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.armv6l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f1049b42726c23bbd44826feaee1ed7ebb465ce"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "621f4ec66fb81b29470d3b30fba2ea5041db29f905e9f3fe95c3ea7c00bab80d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.armv6l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23e3b0a81c359517bac8d5c65e9b2438c15a59fb"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "4bf3c3801054758b102a8c1304567593868c7fea52d56a81345a9088da79daea"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.armv7l-linux-gnueabihf.tar.gz"
[[ghr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23e3b0a81c359517bac8d5c65e9b2438c15a59fb"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "4bf3c3801054758b102a8c1304567593868c7fea52d56a81345a9088da79daea"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.armv7l-linux-musleabihf.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "d51382fb3356ea63a9bd07506e78b06a0f27832e"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "1fa3c757d33e9863b42da341e88704fc53acd0fd82c6cfd255e1ad8e7912985b"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.i686-linux-gnu.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "d51382fb3356ea63a9bd07506e78b06a0f27832e"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "1fa3c757d33e9863b42da341e88704fc53acd0fd82c6cfd255e1ad8e7912985b"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.i686-linux-musl.tar.gz"
[[ghr]]
arch = "i686"
git-tree-sha1 = "76c754a763f00980cb86bcb20d5b49437486ae25"
os = "windows"

    [[ghr.download]]
    sha256 = "7751d59fb4a77ac63c4a05846e58a92bfc8300e66665c25b82b4e469f7ac74ec"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.i686-w64-mingw32.tar.gz"
[[ghr]]
arch = "powerpc64le"
git-tree-sha1 = "45e0f2997f41150a76887b85534992227dc545a5"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "df8c22c39f73d1c6e49ca84c8c00cb19a64d8d1f10daf611a253f3d6aabbf868"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.powerpc64le-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "16468788d07195d31721248c22eea7970f82fef5"
os = "macos"

    [[ghr.download]]
    sha256 = "c905c8922a1991a386ed4fd77edc6a0bff17a68dee5ca42f7d24b7ecc11a2d9a"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.x86_64-apple-darwin.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "c24f19cc47b33dbc92ad367e2509e5870d807406"
libc = "glibc"
os = "linux"

    [[ghr.download]]
    sha256 = "79cdbe26e811861913e970cb5bc8171986eb5bbbbaf30c40f981e9bdef1c982f"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.x86_64-linux-gnu.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "8c5768fca4ffc42bfb11e0f8fd74c6153b1b1f30"
libc = "musl"
os = "linux"

    [[ghr.download]]
    sha256 = "9b80284355d79036f644853d9d8260f100484e02cf5cfd0c24ebc930c2f92b68"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.x86_64-linux-musl.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "3e1befc4fc4ed110b4624c67c58f23ae19dbd8cb"
os = "freebsd"

    [[ghr.download]]
    sha256 = "063f189deccfc4466f9184affec84fccb1be1fdebf4dbc48710ef5a61207286d"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.x86_64-unknown-freebsd.tar.gz"
[[ghr]]
arch = "x86_64"
git-tree-sha1 = "f0555215fa4ee7309ac1af3c407f34e80c811455"
os = "windows"

    [[ghr.download]]
    sha256 = "ee62a1d26aff5ac95f3756297f08ffeb92de4d3f6c3e189b80da848e5728075e"
    url = "https://github.com/JuliaBinaryWrappers/ghr_jll.jl/releases/download/ghr-v0.17.0+0/ghr.v0.17.0.x86_64-w64-mingw32.tar.gz"
